import pytest
from app import app


def test_index_route(client):
    rv = client.get('/')
    assert rv.status_code == 200
    assert b"DroneFlight Planner" in rv.data

def test_upload_returns_obj(client):
    # create a small KMZ in memory
    from tests.test_kmz import KMZ_SAMPLE
    import io
    data = {'file': (io.BytesIO(KMZ_SAMPLE), 'sample.kmz')}
    rv = client.post('/upload-kmz', data=data, content_type='multipart/form-data')
    assert rv.status_code == 200
    json = rv.get_json()
    assert 'geojson' in json
    assert json['geojson']['type'] == 'LineString'
    assert 'obj' in json
    assert json['obj'].startswith('# generated by kmz.kmz_to_obj')


@pytest.fixture

def client():
    app.config['TESTING'] = True
    with app.test_client() as c:
        yield c
