import pytest
from app import app


def test_index_route(client):
    rv = client.get('/')
    assert rv.status_code == 200
    assert b"DroneFlight Planner" in rv.data

def test_upload_returns_obj(client):
    # create a small KMZ in memory
    from tests.test_kmz import KMZ_SAMPLE
    import io
    data = {'file': (io.BytesIO(KMZ_SAMPLE), 'sample.kmz')}
    rv = client.post('/upload-kmz', data=data, content_type='multipart/form-data')
    assert rv.status_code == 200
    json = rv.get_json()
    assert 'geojson' in json
    assert json['geojson']['type'] == 'LineString'
    assert 'obj' in json
    assert json['obj'].startswith('# generated by kmz.kmz_to_obj')


def test_weather_route_fallback(client, monkeypatch):
    # simulate network failure
    import requests
    def bad_get(*args, **kwargs):
        raise Exception("no network")
    monkeypatch.setattr(requests, 'get', bad_get)
    rv = client.get('/weather')
    assert rv.status_code == 200
    text = rv.get_data(as_text=True)
    assert 'unavailable' in text.lower()


def test_weather_route_proxy(client, monkeypatch):
    # simulate successful proxy of remote HTML
    class Dummy:
        text = '<html>ok</html>'
        status_code = 200
        headers = {'Content-Type': 'text/html'}
    import requests
    monkeypatch.setattr(requests, 'get', lambda *args, **kwargs: Dummy)
    rv = client.get('/weather')
    assert rv.status_code == 200
    assert b'ok' in rv.data


def test_static_files_served(client):
    # ensure our local JS/CSS are accessible through Flask's static route
    for path,ctype_sub in [('/static/cesium.js','javascript'),
                       ('/static/widgets.css','css'),
                       ('/static/jszip.min.js','javascript')]:
        rv = client.get(path)
        assert rv.status_code == 200
        # content type may include charset, just check substring
        assert ctype_sub in rv.content_type


@pytest.fixture

def client():
    app.config['TESTING'] = True
    with app.test_client() as c:
        yield c
