import zipfile
from io import BytesIO


def parse_kmz(kmz_bytes: bytes) -> dict:
    """Unpack a KMZ (zip) stream and return the first <coordinates> element as
    a GeoJSON LineString. For simplicity we only handle the very common case
    of a single <Placemark><LineString> path. A real implementation should be
    more robust.
    """
    with zipfile.ZipFile(BytesIO(kmz_bytes)) as z:
        # find the KML file
        kml_name = next((n for n in z.namelist() if n.lower().endswith(".kml")), None)
        if not kml_name:
            raise ValueError("no .kml found in kmz")
        kml_data = z.read(kml_name).decode("utf-8")

    # crude extraction of coordinates; use lxml or BeautifulSoup in prod
    import re
    m = re.search(r"<coordinates>([^<]+)</coordinates>", kml_data)
    if not m:
        raise ValueError("no coordinates in kml")
    coords_text = m.group(1).strip()
    coords = []
    for pair in coords_text.split():
        parts = pair.split(",")
        lon = float(parts[0])
        lat = float(parts[1])
        # if altitude is supplied in the KML we preserve it, otherwise ignore
        if len(parts) > 2 and parts[2]:
            try:
                alt = float(parts[2])
            except ValueError:
                alt = None
        else:
            alt = None
        if alt is not None:
            coords.append([lon, lat, alt])
        else:
            coords.append([lon, lat])
    return {"type": "LineString", "coordinates": coords}


def kmz_to_obj(kmz_bytes: bytes, default_alt: float = 0.0) -> str:
    """Convert a flight path inside a KMZ into a simple OBJ line model.

    The returned string is the contents of a Wavefront OBJ file. Each
    coordinate from the KML is written as a vertex (<code>v</code>) and the
    entire path is represented as a single polyline (<code>l</code>). Altitude
    values encoded in the KML (if any) are used; otherwise <code>default_alt</code>
    is applied to all points.
    """
    geojson = parse_kmz(kmz_bytes)
    coords = geojson.get("coordinates", [])

    lines = ["# generated by droneflight.kmz.kmz_to_obj", "o flight_path"]
    for pt in coords:
        if len(pt) == 3:
            lon, lat, alt = pt
        else:
            lon, lat = pt
            alt = default_alt
        # treat lon as x, lat as y, altitude as z
        lines.append(f"v {lon} {lat} {alt}")

    if len(coords) > 1:
        idxs = " ".join(str(i + 1) for i in range(len(coords)))
        lines.append(f"l {idxs}")

    return "\n".join(lines)
